set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

find_program(SOC_ZIG_EXECUTABLE NAMES zig)
if(NOT SOC_ZIG_EXECUTABLE)
    message(FATAL_ERROR "zig was not found in PATH")
endif()

set(CMAKE_C_COMPILER "${SOC_ZIG_EXECUTABLE}" CACHE FILEPATH "C compiler")
set(CMAKE_C_COMPILER_ARG1 "cc" CACHE STRING "C compiler first argument")
set(CMAKE_C_FLAGS_INIT "--target=aarch64-linux-gnu")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
